name: CI-CD workflow

on: workflow_dispatch

jobs:
  maven:
    name: Maven Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK-17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Unit Test
        run: mvn test

      - name: Build Project
        run: mvn clean package

      - name: Archive Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: target/calculator-app.war
          overwrite: true

  sonar-and-artifactory:
    name: analyse-and-upload
    runs-on: centos-1
    needs: maven
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: target

      - name: Sonar Analysis
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Upload to Artifactory
        env:
          JF_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          JF_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
          JF_URL: ${{ secrets.ARTIFACTORY_URL }}
        run: |
          curl -u "$JF_USERNAME:$JF_PASSWORD" -X PUT \
          -T target/calculator-app.war "$JF_URL/artifactory/java-app-1/dev/calculator-app.war"