name: CI-CD workflow

on: workflow_dispatch

jobs:
  maven:
    name: Maven Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK-17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Unit Test
        run: cd app && mvn test

      - name: Build Project
        run: cd app && mvn clean package

      - name: Archive Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: target/calculator-app.war
          overwrite: true

  sonar-and-artifactory:
    name: analyse-and-upload
    runs-on: centos-1
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Sonar Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          cd app \
          && mvn clean verify sonar:sonar \
          -Dsonar.projectKey=simple-calculator \
          -Dsonar.sources=src/main/java \
          -Dsonar.tests=src/test/java \
          -Dsonar.java.binaries=target/classes \
          -Dsonar.coverage.jacoco.xmlReportPaths=**/jacoco.xml

      - name: Upload to Artifactory
        env:
          JF_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          JF_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
          JF_URL: ${{ secrets.ARTIFACTORY_URL }}
        run: |
          cd app \
          && curl -X PUT -u "$JF_USERNAME:$JF_PASSWORD" \
          -T target/calculator-app.war "$JF_URL/java-app-1/dev/calculator-app.war"

  docker:
    name: docker-build-and-deploy
    runs-on: centos-2
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          cd app \
          && docker build \
          --build-arg="ARTIFACTORY_USERNAME=${{ secrets.ARTIFACTORY_USERNAME }}" \
          --build-arg="ARTIFACTORY_PASSWORD=${{ secrets.ARTIFACTORY_PASSWORD }}" \
          --build-arg="ARTIFACTORY_URL=${{ secrets.ARTIFACTORY_URL }}" \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/demo-calculator:${{ github.run_number }} .

      - name: Push Image to DockerHub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/demo-calculator:${{ github.run_number }}

      - name: Run the container
        run: |
          docker stop calculator-app && docker rm calculator-app \
          && docker run -d -p 9010:8080 --name calculator-app \
          ${{ secrets.DOCKERHUB_USERNAME }}/demo-calculator:${{ github.run_number }}