name: Docker workflow

on: workflow_dispatch

jobs:
  docker:
    name: docker-build-and-deploy
    runs-on: centos-2
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        id: login
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        id: build
        run: |
          cd mvcapp \
          && docker build \
          --build-arg="ARTIFACTORY_USERNAME=${{ secrets.ARTIFACTORY_USERNAME }}" \
          --build-arg="ARTIFACTORY_PASSWORD=${{ secrets.ARTIFACTORY_PASSWORD }}" \
          --build-arg="ARTIFACTORY_URL=${{ secrets.ARTIFACTORY_URL }}" \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/demo-calculator:${{ github.run_number }} .

      - name: Push Image to DockerHub
        id: push
        if: steps.build.outcome == 'success'
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/demo-calculator:${{ github.run_number }}

      - name: Run the container
        if: steps.build.outcome == 'success'
        run: |
          docker ps -q -a --filter name="^calculator-app$" | xargs -r docker stop calculator-app
          docker ps -q -a --filter name="^calculator-app$" | xargs -r docker rm calculator-app
          docker run -d -p 9010:8080 --name calculator-app \
          ${{ secrets.DOCKERHUB_USERNAME }}/demo-calculator:${{ github.run_number }}
