name: Selenium workflow

on: workflow_dispatch

jobs:
  selenium:
    name: selenium-automation-test
    runs-on: centos-2
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Test
        run: |
          export JAVA_HOME=/opt/jdk-17.0.2/
          export M2_HOME=/opt/apache-maven-3.9.6/
          export PATH=$PATH:$M2_HOME/bin
          mvn --version
          mvn -f selenium-testing/pom.xml test
