name: Selenium workflow

on: workflow_dispatch

jobs:
  selenium:
    name: selenium-automation-test
    runs-on: centos-2
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Test
        run: |
          echo $PATH
          echo M2_HOME
          cd selenium-testing
          pwd
          mvn --version
          mvn test
